# Generated by Django 4.1.2 on 2023-04-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maintable',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('promotion_name', models.TextField()),
                ('sales_country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detailtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.TextField()),
                ('sales_country', models.TextField()),
                ('sales_volume', models.IntegerField()),
                ('negative_comment', models.IntegerField()),
                ('price', models.FloatField()),
                ('invoice_date', models.TextField()),
                ('supplier', models.TextField()),
                ('brand_name', models.TextField()),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='shopping_table.maintable')),
            ],
        ),
    ]
