# Generated by Django 4.1.2 on 2023-04-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtable',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
