# Generated by Django 4.1.2 on 2023-04-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_table', '0002_alter_detailtable_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailtable',
            old_name='product_id',
            new_name='product',
        ),
    ]
