# Generated by Django 4.1.2 on 2023-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_table', '0004_rename_product_detailtable_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtable',
            name='brand_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='invoice_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='negative_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='promotion_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='sales_country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='sales_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detailtable',
            name='supplier',
            field=models.TextField(null=True),
        ),
    ]
