# Generated by Django 4.1.2 on 2023-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('promotion_name', models.TextField()),
                ('sales_country', models.TextField()),
                ('added_to_cart', models.BooleanField(default=False)),
            ],
        ),
    ]
