# Generated by Django 4.1.2 on 2023-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='promotion_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sales_country',
            field=models.TextField(null=True),
        ),
    ]
